### ISSUE TITLE
python-psutil-3.1.1-1.fc24.x86_64 breaks tracer

### ISSUE THREAD

**Issue by nirik** [FrostyX/tracer#40] opened 2015-07-22 03:31 UTC
On upgrading to python-psutil-3.1.1-1.fc24.x86_64:

Tracer:
  Program 'tracer' crashed with following error:

b'Traceback (most recent call last):\n  File "/bin/tracer", line 34, in <module>\n    tracer.main.run()\n  File "/usr/lib/python2.7/site-packages/tracer/main.py", line 42, in run\n    return router.dispatch()\n  File "/usr/lib/python2.7/site-packages/tracer/resources/router.py", line 54, in dispatch\n    from tracer.controllers.default import DefaultController\n  File "/usr/lib/python2.7/site-packages/tracer/controllers/default.py", line 20, in <module>\n    from tracer.views.default import DefaultView\n  File "/usr/lib/python2.7/site-packages/tracer/views/default.py", line 6, in <module>\n    from tracer.resources.applications import Applications\n  File "/usr/lib/python2.7/site-packages/tracer/resources/applications.py", line 24, in <module>\n    from tracer.resources.collections import ApplicationsCollection\n  File "/usr/lib/python2.7/site-packages/tracer/resources/collections.py", line 22, in <module>\n    from psutil import NoSuchProcess\n  File "/usr/lib64/python2.7/site-packages/psutil/__init__.py", line 62, in <module>\n    from . import _pslinux as _psplatform\n  File "/usr/lib64/python2.7/site-packages/psutil/_pslinux.py", line 23, in <module>\n    from . import _psutil_linux as cext\nImportError: cannot import name _psutil_linux\n'
Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience
Complete!

**Comment by FrostyX** [comment] 2015-07-22 08:37
Hello @nirik, thank you for the feedback. I am aware that you reported me several issues. My apologies, I am not running fedora rawhide anywhere, so you encountered them sooner than me. I will try at least run tests on rawhide, it should discover this kind of issues.

There is the formated traceback


	Traceback (most recent call last):
	  File "/bin/tracer", line 34, in <module>
	    tracer.main.run()
	  File "/usr/lib/python2.7/site-packages/tracer/main.py", line 42, in run
	    return router.dispatch()
	  File "/usr/lib/python2.7/site-packages/tracer/resources/router.py", line 54, in dispatch
	    from tracer.controllers.default import DefaultController
	  File "/usr/lib/python2.7/site-packages/tracer/controllers/default.py", line 20, in <module>
	    from tracer.views.default import DefaultView
	  File "/usr/lib/python2.7/site-packages/tracer/views/default.py", line 3, in <module>
	    from tracer.resources.applications import Applications
	  File "/usr/lib/python2.7/site-packages/tracer/resources/applications.py", line 24, in <module>
	    from tracer.resources.collections import ApplicationsCollection
	  File "/usr/lib/python2.7/site-packages/tracer/resources/collections.py", line 22, in <module>
	    from psutil import NoSuchProcess
	  File "/usr/lib64/python2.7/site-packages/psutil/__init__.py", line 62, in <module>
	    from . import _pslinux as _psplatform
	  File "/usr/lib64/python2.7/site-packages/psutil/_pslinux.py", line 23, in <module>
	    from . import _psutil_linux as cext
	ImportError: cannot import name _psutil_linux

**Comment by nirik** [comment] 2015-07-22 08:55
No apologies needed. ;) It seems python-psutil changed under you... 

I assume you prefer issues here? Or should I open them in bugzilla.redhat.com? 

Happy to provide info or test.

**Comment by FrostyX** [comment] 2015-07-22 09:00
It seems that the issue isn't in tracer's code

    python -c "import psutil"
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib64/python2.7/site-packages/psutil/__init__.py", line 62, in <module>
        from . import _pslinux as _psplatform
      File "/usr/lib64/python2.7/site-packages/psutil/_pslinux.py", line 23, in <module>
        from . import _psutil_linux as cext
    ImportError: cannot import name _psutil_linux

Altough when I install `psutil-3.1.1` through `pip`, it works just fine. Well, it fails on different traceback, because there was some API removal in 3.0, but at least psutil can be imported. So, maybe this can be a bug in fedora package?

**Comment by nirik** [comment] 2015-07-22 09:03
Yeah, could be. Added a note to: 

https://bugzilla.redhat.com/show_bug.cgi?id=1231497

**Comment by FrostyX** [comment] 2015-07-22 09:14
Thank you,
added CC to myself.

**Comment by michel-slm** [comment] 2015-07-22 13:46
My bad, there are permission warnings on the *.so files when building under mock, and my attempt to fix it in -1 ended up excluding said *.so files. @nirik could you try again with -2 ?

**Comment by FrostyX** [comment] 2015-07-27 19:37
It should be fixed now, according to the linked issue on RedHat bugzilla. I am closing it.
Thank you guys.

**Closed by FrostyX** 2015-07-27 19:37 UTC
Labels: bug, core, critical
