### ISSUE TITLE
Fedora 32 Workstation: TypeError: update() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by M-Alonzo** [FrostyX/tracer#147] opened 2020-05-29 06:22 UTC
This is the first time I've noticed this error.

> Tracer:
>  Call to Tracer API ended unexpectedly:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/site-packages/dnf-plugins/tracer.py", line 67, in transaction
>     tracer.render()
>   File "/usr/lib/python3.8/site-packages/dnf-plugins/tracer.py", line 92, in render
>     return view.render()
>   File "/usr/lib/python3.8/site-packages/tracer/views/default.py", line 59, in render
>     {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
>   File "/usr/lib/python3.8/site-packages/tracer/views/default.py", line 20, in with_helpers_content
>     applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
>   File "/usr/lib/python3.8/site-packages/tracer/resources/collections.py", line 34, in sorted
>     self.replace_values(attribute, None, "")
>   File "/usr/lib/python3.8/site-packages/tracer/resources/collections.py", line 30, in replace_values
>     app.update(attribute, required_value)
> TypeError: update() takes 2 positional arguments but 3 were given

**Comment by FrostyX** [comment] 2020-05-29 11:22
Hello @M-Alonzo.
thank you for the feedback. PR #144 fixes this issue. It is not released yet, though.

There are already multiple tickets for this issue, so I am going to close this one as a duplicate of #113.

**Closed by FrostyX** 2020-05-29 11:22 UTC
