### ISSUE TITLE
tracer -s firefox fails with traceback: AttributeError: 'NoneType' object has no attribute 'files'

### ISSUE THREAD

**Issue by ryran** [FrostyX/tracer#37] opened 2015-06-24 19:44 UTC
```
╔═[rsaw@xala 15:43 ~]
╚═══{1} $ sudo tracer -s terminator
* terminator
    Package:     terminator
    Description: Store and run multiple GNOME terminals in one window
    Type:        Application
    State:       terminator has been started by rsaw 5 minutes ago. PID - 21192
╔═[rsaw@xala 15:43 ~]
╚═══{0} $ sudo tracer -s firefox
Traceback (most recent call last):
  File "/bin/tracer", line 34, in <module>
    tracer.main.run()
  File "/usr/lib/python2.7/site-packages/tracer/main.py", line 42, in run
    return router.dispatch()
  File "/usr/lib/python2.7/site-packages/tracer/resources/router.py", line 40, in dispatch
    controller.render()
  File "/usr/lib/python2.7/site-packages/tracer/controllers/helper.py", line 39, in render
    self.print_helper(app_name, self.args)
  File "/usr/lib/python2.7/site-packages/tracer/controllers/helper.py", line 54, in print_helper
    try: affected_by = tr.trace_application(app_name)
  File "/usr/lib/python2.7/site-packages/tracer/resources/tracer.py", line 130, in trace_application
    processes.update(self._affecting_children(process, packages))
  File "/usr/lib/python2.7/site-packages/tracer/resources/tracer.py", line 162, in _affecting_children
    processes.update(self._affecting_processes(child, packages))
  File "/usr/lib/python2.7/site-packages/tracer/resources/tracer.py", line 135, in _affecting_processes
    process_files = process.files
  File "/usr/lib/python2.7/site-packages/tracer/resources/processes.py", line 83, in __getattr__
    return getattr(self._process, item)
AttributeError: 'NoneType' object has no attribute 'files'
```

**Comment by FrostyX** [comment] 2015-06-27 15:57
Hello Ryan,
thank you for the feedback.

Please try to run `sudo tracer -s firefox` once again. Does it fail always, or it happened just once?
It works for me correctly, so I guess that something broke up while tracer was searching and its not related to firefox at all.

Also, please, what version do you use?
Thank you

**Comment by ryran** [comment] 2015-06-30 05:32
Hi there.
I'm on Fedora 22, so I'm using the latest available distro-provided version, i.e., `tracer-0.5.8-1.fc22`. And yes, the command always fails (ever since I first tried it). I haven't tried `tracer -s` on tons of commands, but firefox is the only one that fails.

**Comment by FrostyX** [comment] 2015-07-01 08:51
Heh, that's interesting.
I also use F22 and latest package and both commands works for me. I think it will be fun to debug it :-D

Soon, I will look at it,
thank you.

**Comment by sean797** [comment] 2018-04-19 12:50
I think this was caused by our dynamic use of `psutil`, since https://github.com/FrostyX/tracer/commit/08fed6a4a7ee1134c9d464df30308e9e13a706c9 fixed that I'm going to close this issue, please re-open this if you hit this issue again.

**Closed by sean797** 2018-04-19 12:50 UTC
