### ISSUE TITLE
Wrong application type - tracer says that nano and vim needs session restart

### ISSUE THREAD

**Issue by FrostyX** [FrostyX/tracer#119] opened 2018-12-05 21:04 UTC
Tracer for some reason suggests that I should restart the session to deal with updated nano.

    * nano
        Package:     nano
        Description: A small text editor
        Type:        Session
        State:       nano has been started by jkadlcik 33 seconds ago. PID - 5301

        Affected by: 
            nano
                /usr/bin/nano

        How to restart:
            You will have to log out & log in again

**Comment by FrostyX** [comment] 2018-12-05 21:16
Seems to be caused by 7ea01572

**Comment by elyscape** [comment] 2018-12-10 22:58
It looks like this is caused by the way tracer is detecting sessions. To decide if a process is a session, [tracer checks to see if `Process.terminal()` returns a value][is_session]. Unfortunately, that's not what `Process.terminal()` does; if the process is attached to a terminal, it returns the path to the terminal. As a result, anything attached to a terminal will be interpreted as being a session. One potential solution to this would be to do something like this:
```python
@property
def is_session(self):
    terminal = self.terminal()
    if terminal is None:
        return None
    parent = self.parent()
    if parent is None or terminal != parent.terminal():
        return True
```
With this change, a process is a session if it has a terminal attached and either has no parent or its parent has a different terminal attached. This isn't foolproof logic, but seems better than what is currently implemented.

[is_session]: https://github.com/FrostyX/tracer/blob/1932c5fa34c75b019ae0637a4970c73a5c8ce796/tracer/resources/processes.py#L247-L249

**Closed** 2018-12-17 09:21 UTC
