### ISSUE TITLE
Constant failures with dnf upgrade on Fedora 28

### ISSUE THREAD

**Issue by Tyrbiter** [FrostyX/tracer#114] opened 2018-09-20 11:24 UTC
All rpms update but tracer run always ends like this.

Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 66, in transaction
    tracer = TracerFacade(packages)
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 79, in __init__
    self.apps = self.get_apps(packages)
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 84, in get_apps
    return query.from_packages(packages).now().affected_applications().get()
  File "/usr/lib/python3.6/site-packages/tracer/query.py", line 72, in get
    return self._method(**self._kwargs)
  File "/usr/lib/python3.6/site-packages/tracer/resources/tracer.py", line 93, in trace_affected
    memory = self._memory(user)
  File "/usr/lib/python3.6/site-packages/tracer/resources/memory.py", line 38, in dump_memory
    for file in process.files:
  File "/usr/lib/python3.6/site-packages/tracer/resources/processes.py", line 197, in files
    if os.path.isfile(arg):
  File "/usr/lib64/python3.6/genericpath.py", line 30, in isfile
    st = os.stat(path)
ValueError: embedded null byte

**Comment by FrostyX** [comment] 2020-05-27 21:16
Hello, I am sorry for not responding here.
I was not able to reproduce the issue and then it was totally forgotten.

Do you know if this still happens? In 9ed9eed6 @jturel improved the logic so this issue may have been accidentally fixed by that.

**Comment by jturel** [comment] 2020-05-28 15:18
It very well may have :)

**Comment by FrostyX** [comment] 2020-06-05 19:39
Let's be optimistic and hope that the commit fixed it. @Tyrbiter if it occurs again, please reopen.

**Closed by FrostyX** 2020-06-05 19:39 UTC
