### ISSUE TITLE
Crashed on `dnf update`

### ISSUE THREAD

**Issue by pvalena** [FrostyX/tracer#102] opened 2018-02-07 11:41 UTC
Running via dnf plugin(`python3-dnf-plugin-tracer`), crashes on `dnf update` on Fedora 27:

```
 [ . . . ]
                           984/991
  Verifying        : python-rhsm-certificates-1.20.1-3.fc27.x86_64                                                           985/991
  Verifying        : libertas-usb8388-firmware-2:20171215-81.git2451bb22.fc27.noarch                                         986/991
  Verifying        : python-srpm-macros-3-23.fc27.noarch                                                                     987/991
  Verifying        : python2-2.7.14-4.fc27.x86_64                                                                            988/991
  Verifying        : libfastjson-0.99.7-1.fc27.x86_64                                                                        989/991
  Verifying        : libfdt-1.4.5-1.fc27.x86_64                                                                              990/991
  Verifying        : libffado-2.3.0-7.fc27.x86_64                                                                            991/991
/usr/lib64/python3.6/re.py:212: FutureWarning: split() requires a non-empty pattern match.
  return _compile(pattern, flags).split(string, maxsplit)

Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 66, in transaction
    tracer = TracerFacade(packages)
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 79, in __init__
    self.apps = self.get_apps(packages)
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 84, in get_apps
    return query.from_packages(packages).now().affected_applications().get()
  File "/usr/lib/python3.6/site-packages/tracer/query.py", line 72, in get
    return self._method(**self._kwargs)
  File "/usr/lib/python3.6/site-packages/tracer/resources/tracer.py", line 99, in trace_affected
    for file in self._PACKAGE_MANAGER.package_files(package.name):
  File "/usr/lib/python3.6/site-packages/tracer/resources/PackageManager.py", line 55, in package_files
    return self.package_managers[0].package_files(pkg_name)
  File "/usr/lib/python3.6/site-packages/tracer/packageManagers/dnf.py", line 35, in package_files
    return super(Dnf, self).package_files(pkg_name)
  File "/usr/lib/python3.6/site-packages/tracer/packageManagers/rpm.py", line 94, in package_files
    fi = rpm.fi(next(mi))
StopIteration
DNF 
Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience

Removed:
  kernel.x86_64 4.14.7-300.fc27                                  kernel-core.x86_64 4.14.7-300.fc27
  kernel-debug-core.x86_64 4.14.7-300.fc27                       kernel-debug-devel.x86_64 4.14.7-300.fc27

[ . . . ]
```

There was only one other interesting thing:
```
[ . . . ]
                                                         463/991
  Verifying        : tzdata-2018c-1.fc27.noarch                                                                              464/991
  Verifying        : tzdata-java-2018c-1.fc27.noarch                                                                         465/991
  Verifying        : unbound-libs-1.6.8-1.fc27.x86_64                                                                        466/991
unetbootin-657-1.fc27.x86_64 was supposed to be installed but is not!
  Verifying        : unetbootin-657-1.fc27.x86_64                                                                            467/991
  Verifying        : unrar-5.5.8-1.fc27.x86_64                                                                               468/991
  Verifying        : upower-0.99.7-1.fc27.x86_64                                                                             469/991
  Verifying        : urw-base35-bookman-fonts-20170801-4.fc27.noarch         

[ . . . ]

Failed:
  unetbootin.x86_64 657-1.fc27

Error: Transaction failed

```

HIH.

**Comment by sean797** [comment] 2018-04-18 21:04
I think this was caused by our dynamic use of `psutil`, since https://github.com/FrostyX/tracer/commit/08fed6a4a7ee1134c9d464df30308e9e13a706c9 fixed that I'm going to close this issue, please re-open this if you hit this issue again.

**Closed by sean797** 2018-04-18 21:04 UTC
