### ISSUE TITLE
Received error below when updating a Fedora 25 instance with dnf

### ISSUE THREAD

**Issue by zipnemud** [FrostyX/tracer#97] opened 2017-11-25 02:38 UTC
Since F25 is almost at EOL, I'm not sure if it is worth pursuing, but I'll leave it up to you.

Tracer:
  Program 'tracer' crashed with following error:

```
Traceback (most recent call last):
File "/usr/bin/tracer", line 34, in <module>
    tracer.main.run()
File "/usr/lib/python3.5/site-packages/tracer/main.py", line 45, in run
    return router.dispatch()
File "/usr/lib/python3.5/site-packages/tracer/resources/router.py", line 58, in dispatch
    controller.render()
File "/usr/lib/python3.5/site-packages/tracer/controllers/default.py", line 71, in render
    view.render()
File "/usr/lib/python3.5/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
File "/usr/lib/python3.5/site-packages/tracer/views/default.py", line 22, in with_helpers_content
    helpers = "; ".join(application.helpers)
File "/usr/lib/python3.5/site-packages/tracer/resources/applications.py", line 241, in helpers
    if not self.helper_contains_formating:
File "/usr/lib/python3.5/site-packages/tracer/resources/applications.py", line 225, in helper_contains_formating
    return bool(re.search("\\{.*\\}", self.helper))
File "/usr/lib/python3.5/site-packages/tracer/resources/applications.py", line 217, in helper
    helper = self._attributes["helper"] if self._attributes["helper"] else Applications._helper(self)
File "/usr/lib/python3.5/site-packages/tracer/resources/applications.py", line 120, in _helper
    if app.type == Applications.TYPES["DAEMON"]:
File "/usr/lib/python3.5/site-packages/tracer/resources/applications.py", line 202, in type
    elif self.is_session:
File "/usr/lib/python3.5/site-packages/tracer/resources/applications.py", line 194, in is_session
    if re.search(\'ssh-.*-session\', str(self.name)):
File "/usr/lib/python3.5/site-packages/tracer/resources/applications.py", line 271, in name
    if not bus.has_service_property_from_pid(self.instances[0].pid,\'PAMName\'):
File "/usr/lib/python3.5/site-packages/tracer/resources/SystemdDbus.py", line 39, in has_service_property_from_pid
    proxy = dbus.SystemBus().get_object(\'org.freedesktop.systemd1\', self.unit_path_from_pid(pid))
File "/usr/lib64/python3.5/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
File "/usr/lib64/python3.5/site-packages/dbus/proxies.py", line 244, in __init__
    _dbus_bindings.validate_object_path(object_path)
TypeError: validate_object_path() argument 1 must be str, not bool

**Comment by sean797** [comment] 2018-04-19 13:04
This was caused by our dynamic use of `psutil`, since https://github.com/FrostyX/tracer/commit/08fed6a4a7ee1134c9d464df30308e9e13a706c9 fixed that I'm going to close this issue, please re-open this if you hit this issue again.

**Closed by sean797** 2018-04-19 13:04 UTC
