### ISSUE TITLE
Traceback report

### ISSUE THREAD

**Issue by opuk** [FrostyX/tracer#101] opened 2018-01-24 13:43 UTC
During a dnf update on Fedora 27:

```
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tracer/resources/collections.py", line 29, in sorted
    return sorted(self, key=methodcaller(attribute))
TypeError: 'str' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.6/site-packages/tracer/resources/collections.py", line 31, in sorted
    return sorted(self, key=attrgetter(attribute))
TypeError: '<' not supported between instances of 'NoneType' and 'str'

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience
```

**Comment by FrostyX** [comment] 2018-01-27 17:49
I have difficulties with reproducing this issue. Does this happen all the time?

**Comment by FrostyX** [comment] 2018-01-27 17:52
I am closing this as a duplicate of #99, please let's continue the discussion there.

**Closed by FrostyX** 2018-01-27 17:52 UTC
