### ISSUE TITLE
Call to Tracer API ended unexpectedly

### ISSUE THREAD

**Issue by Jonrysh** [FrostyX/tracer#173] opened 2021-07-25 09:26 UTC
The [tracer-bug.log](https://github.com/FrostyX/tracer/files/6873616/tracer-bug.log)ed error was produced by "sudo dnf upgrade", and requested that I submit the error log, which is [tracer-bug.log](https://github.com/FrostyX/tracer/files/6873616/tracer-bug.log)ed.  My version of dnf has python3-dnf-plugin-tracer installed.

I intended the first sentence to read:
The attached error was produced by "sudo dnf upgrade", and requested that I submit the error log, which is attached.
But clicking on "dragging & dropping, SELECTING or pasting" has garbled it.  The log file attached is called tracer-bug.log.  Please forgive my ignorance.

**Comment by FrostyX** [comment] 2021-07-25 15:26
Hello @Jonrysh,
thank you for the report.

I think this is a duplicate of #156 and should be fixed in PR #169.
Let me close this one, so we don't split the discussion into two tickets.

The new release containing this fix should be out this week.

**Closed by FrostyX** 2021-07-25 15:26 UTC
