### ISSUE TITLE
instances[0] - IndexError: list index out of range

### ISSUE THREAD

**Issue by xosevp** [FrostyX/tracer#96] opened 2017-10-23 22:07 UTC
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 74, in render
    blocks.append({"content": note_content()})
  File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 53, in note_content
    view.assign("session_count", self.args.applications.count_type(Applications.TYPES["SESSION"]))
  File "/usr/lib/python3.6/site-packages/tracer/resources/collections.py", line 57, in count_type
    if application.type == app_type:
  File "/usr/lib/python3.6/site-packages/tracer/resources/applications.py", line 204, in type
    elif self.is_service:
  File "/usr/lib/python3.6/site-packages/tracer/resources/applications.py", line 212, in is_service
    return SystemdDbus().unit_path_from_id("{0}.service".format(self.name))
  File "/usr/lib/python3.6/site-packages/tracer/resources/applications.py", line 271, in name
    if not bus.has_service_property_from_pid(self.instances[0].pid,'PAMName'):
IndexError: list index out of range

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience

**Comment by rathann** [comment] 2017-12-28 21:22
Same here, Fedora 26, full log:
```
# dnf update -x kernel\*
Last metadata expiration check: 0:00:25 ago on Thu 28 Dec 2017 22:19:00 CET.
Dependencies resolved.
========================================================================================================================
 Package                        Arch                    Version                          Repository                Size
========================================================================================================================
Upgrading:
 libjpeg-turbo                  x86_64                  1.5.3-1.fc26                     updates                  152 k
 man-db                         x86_64                  2.7.6.1-8.fc26                   updates                  872 k

Transaction Summary
========================================================================================================================
Upgrade  2 Packages

Total download size: 1.0 M
Is this ok [y/N]: y
Downloading Packages:
(1/2): libjpeg-turbo-1.5.3-1.fc26.x86_64.rpm                                            651 kB/s | 152 kB     00:00    
(2/2): man-db-2.7.6.1-8.fc26.x86_64.rpm                                                 2.8 MB/s | 872 kB     00:00    
------------------------------------------------------------------------------------------------------------------------
Total                                                                                   1.2 MB/s | 1.0 MB     00:00     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Running scriptlet: None                                                                                           1/1 
  Preparing        :                                                                                                1/1 
  Running scriptlet: man-db-2.7.6.1-8.fc26.x86_64                                                                   1/4 
  Upgrading        : man-db-2.7.6.1-8.fc26.x86_64                                                                   1/4 
  Running scriptlet: man-db-2.7.6.1-8.fc26.x86_64                                                                   1/4 
  Upgrading        : libjpeg-turbo-1.5.3-1.fc26.x86_64                                                              2/4 
  Running scriptlet: libjpeg-turbo-1.5.3-1.fc26.x86_64                                                              2/4 
  Cleanup          : man-db-2.7.6.1-7.fc26.x86_64                                                                   3/4 
  Running scriptlet: man-db-2.7.6.1-7.fc26.x86_64                                                                   3/4 
  Cleanup          : libjpeg-turbo-1.5.1-0.fc26.x86_64                                                              4/4 
  Running scriptlet: libjpeg-turbo-1.5.1-0.fc26.x86_64                                                              4/4 
  Running scriptlet: man-db-2.7.6.1-8.fc26.x86_64                                                                   4/4 
Running as unit: run-r04ef408d196e427d91a8b953b513b77b.service
  Verifying        : libjpeg-turbo-1.5.3-1.fc26.x86_64                                                              1/4 
  Verifying        : man-db-2.7.6.1-8.fc26.x86_64                                                                   2/4 
  Verifying        : libjpeg-turbo-1.5.1-0.fc26.x86_64                                                              3/4 
  Verifying        : man-db-2.7.6.1-7.fc26.x86_64                                                                   4/4 
/usr/lib64/python3.6/re.py:212: FutureWarning: split() requires a non-empty pattern match.
  return _compile(pattern, flags).split(string, maxsplit)

Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 60, in render
    {"title": "  * " + _("These applications manually:"), "content": without_helpers_content()},
  File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 30, in without_helpers_content
    apps = self.args.applications.exclude_types(Applications.TYPES["ERASED"]).without_helpers().sorted("name")
  File "/usr/lib/python3.6/site-packages/tracer/resources/collections.py", line 47, in exclude_types
    return ApplicationsCollection(applications)
  File "/usr/lib/python3.6/site-packages/tracer/resources/collections.py", line 46, in <lambda>
    applications = filter(lambda app: app.type not in app_types, self)
  File "/usr/lib/python3.6/site-packages/tracer/resources/applications.py", line 204, in type
    elif self.is_service:
  File "/usr/lib/python3.6/site-packages/tracer/resources/applications.py", line 212, in is_service
    return SystemdDbus().unit_path_from_id("{0}.service".format(self.name))
  File "/usr/lib/python3.6/site-packages/tracer/resources/applications.py", line 271, in name
    if not bus.has_service_property_from_pid(self.instances[0].pid,'PAMName'):
IndexError: list index out of range

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience

Upgraded:
  libjpeg-turbo.x86_64 1.5.3-1.fc26                             man-db.x86_64 2.7.6.1-8.fc26                            

Complete!
```

**Comment by sean797** [comment] 2018-04-18 20:53
I think this was caused by our dynamic use of `psutil`, since https://github.com/FrostyX/tracer/commit/08fed6a4a7ee1134c9d464df30308e9e13a706c9 fixed that I'm going to close this issue, please re-open this if you hit this issue again.

**Closed by sean797** 2018-04-18 20:53 UTC
