### ISSUE TITLE
Traceback report

### ISSUE THREAD

**Issue by azanegin** [FrostyX/tracer#78] opened 2017-04-03 09:29 UTC
```
b'Traceback (most recent call last):\n  File "/usr/lib64/python3.5/site-packages/psutil/_pslinux.py", line 962, in wrapper\n    return fun(self, *args, **kwargs)\n  File "/usr/lib64/python3.5/site-packages/psutil/_pslinux.py", line 1014, in name\n    name = self._parse_stat_file()[0]\n  File "/usr/lib64/python3.5/site-packages/psutil/_pslinux.py", line 993, in _parse_stat_file\n    with open_binary("%s/%s/stat" % (self._procfs_path, self.pid)) as f:\n  File "/usr/lib64/python3.5/site-packages/psutil/_pslinux.py", line 180, in open_binary\n    return open(fname, "rb", **kwargs)\nFileNotFoundError: [Errno 2] No such file or directory: \'/proc/309/stat\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/bin/tracer", line 34, in <module>\n    tracer.main.run()\n  File "/usr/lib/python3.5/site-packages/tracer/main.py", line 45, in run\n    return router.dispatch()\n  File "/usr/lib/python3.5/site-packages/tracer/resources/router.py", line 58, in dispatch\n    controller.render()\n  File "/usr/lib/python3.5/site-packages/tracer/controllers/default.py", line 71, in render\n    view.render()\n  File "/usr/lib/python3.5/site-packages/tracer/views/default.py", line 59, in render\n    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},\n  File "/usr/lib/python3.5/site-packages/tracer/views/default.py", line 20, in with_helpers_content\n    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")\n  File "/usr/lib/python3.5/site-packages/tracer/resources/collections.py", line 38, in with_helpers\n    return ApplicationsCollection(applications)\n  File "/usr/lib/python3.5/site-packages/tracer/resources/collections.py", line 37, in <lambda>\n    applications = filter(lambda app: app.helper, self)\n  File "/usr/lib/python3.5/site-packages/tracer/resources/applications.py", line 201, in helper\n    helper = self._attributes["helper"] if self._attributes["helper"] else Applications._helper(self)\n  File "/usr/lib/python3.5/site-packages/tracer/resources/applications.py", line 127, in _helper\n    elif app.type == Applications.TYPES["SESSION"]:\n  File "/usr/lib/python3.5/site-packages/tracer/resources/applications.py", line 192, in type\n    return Applications.TYPES["DAEMON"] if self.has_service_file else self._attributes["type"]\n  File "/usr/lib/python3.5/site-packages/tracer/resources/applications.py", line 196, in has_service_file\n    return os.path.isfile("/usr/lib/systemd/system/{0}.service".format(self.name))\n  File "/usr/lib/python3.5/site-packages/tracer/resources/applications.py", line 252, in name\n    if self.is_interpreted:\n  File "/usr/lib/python3.5/site-packages/tracer/resources/applications.py", line 188, in is_interpreted\n    return self.instances and self.instances[0].is_interpreted\n  File "/usr/lib/python3.5/site-packages/tracer/resources/processes.py", line 182, in is_interpreted\n    return self.name() in ["python"]\n  File "/usr/lib/python3.5/site-packages/tracer/resources/processes.py", line 67, in name\n    return self._attr("name")\n  File "/usr/lib/python3.5/site-packages/tracer/resources/processes.py", line 93, in _attr\n    try: return attr()\n  File "/usr/lib64/python3.5/site-packages/psutil/__init__.py", line 557, in name\n    name = self._proc.name()\n  File "/usr/lib64/python3.5/site-packages/psutil/_pslinux.py", line 968, in wrapper\n    raise NoSuchProcess(self.pid, self._name)\npsutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=309, name=\'chrome\')\n'
Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience
Complete!

```

Got that on my daily "dnf upgrade" routine. I mean, dunno if that matters, but the text asks to post it here... Anyway, if anybody cares, feel free to ask for any useful info.

**Comment by sean797** [comment] 2017-05-08 15:32
Thanks @azanegin 
For people reference a readable formatted version of the above:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/psutil/_pslinux.py", line 962, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/lib64/python3.5/site-packages/psutil/_pslinux.py", line 1014, in name
    name = self._parse_stat_file()[0]
  File "/usr/lib64/python3.5/site-packages/psutil/_pslinux.py", line 993, in _parse_stat_file
    with open_binary("%s/%s/stat" % (self._procfs_path, self.pid)) as f:
  File "/usr/lib64/python3.5/site-packages/psutil/_pslinux.py", line 180, in open_binary
    return open(fname, "rb", **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: \'/proc/309/stat\'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/tracer", line 34, in <module>
    tracer.main.run()
  File "/usr/lib/python3.5/site-packages/tracer/main.py", line 45, in run
    return router.dispatch()
  File "/usr/lib/python3.5/site-packages/tracer/resources/router.py", line 58, in dispatch
    controller.render()
  File "/usr/lib/python3.5/site-packages/tracer/controllers/default.py", line 71, in render
    view.render()
  File "/usr/lib/python3.5/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.5/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.5/site-packages/tracer/resources/collections.py", line 38, in with_helpers
    return ApplicationsCollection(applications)
  File "/usr/lib/python3.5/site-packages/tracer/resources/collections.py", line 37, in <lambda>
    applications = filter(lambda app: app.helper, self)
  File "/usr/lib/python3.5/site-packages/tracer/resources/applications.py", line 201, in helper
    helper = self._attributes["helper"] if self._attributes["helper"] else Applications._helper(self)
  File "/usr/lib/python3.5/site-packages/tracer/resources/applications.py", line 127, in _helper
    elif app.type == Applications.TYPES["SESSION"]:
  File "/usr/lib/python3.5/site-packages/tracer/resources/applications.py", line 192, in type
    return Applications.TYPES["DAEMON"] if self.has_service_file else self._attributes["type"]
  File "/usr/lib/python3.5/site-packages/tracer/resources/applications.py", line 196, in has_service_file
    return os.path.isfile("/usr/lib/systemd/system/{0}.service".format(self.name))
  File "/usr/lib/python3.5/site-packages/tracer/resources/applications.py", line 252, in name
    if self.is_interpreted:
  File "/usr/lib/python3.5/site-packages/tracer/resources/applications.py", line 188, in is_interpreted
    return self.instances and self.instances[0].is_interpreted
  File "/usr/lib/python3.5/site-packages/tracer/resources/processes.py", line 182, in is_interpreted
    return self.name() in ["python"]
  File "/usr/lib/python3.5/site-packages/tracer/resources/processes.py", line 67, in name
    return self._attr("name")
  File "/usr/lib/python3.5/site-packages/tracer/resources/processes.py", line 93, in _attr
    try: return attr()
  File "/usr/lib64/python3.5/site-packages/psutil/__init__.py", line 557, in name
    name = self._proc.name()
  File "/usr/lib64/python3.5/site-packages/psutil/_pslinux.py", line 968, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=309, name=\'chrome\')

**Comment by sean797** [comment] 2018-04-18 20:52
I think this was caused by our dynamic use of `psutil`, since https://github.com/FrostyX/tracer/commit/08fed6a4a7ee1134c9d464df30308e9e13a706c9 fixed that I'm going to close this issue, please re-open this if you hit this issue again.

**Closed by sean797** 2018-04-18 20:53 UTC
